### ISSUE TITLE
users->getMeBoards() brings "Undefined index: page"

### ISSUE THREAD

**Issue by webresh** [dirkgroenen/Pinterest-API-PHP#1]
Hi there!
Currently Pinterest API response doesn't have a 'page' value.
There is only a 'data' field in response, and it is stated here:
/pinterest-api-php/tests/Pinterest/responses/UsersTest/testGetMeBoards.json

In collection.php:90 there is
        // Add pagination object
        $this->pagination = $this->response->page;

It makes /Transport/Response.php:70 answering
        Undefined index: page

thanks

**Comment by dirkgroenen** [comment]
Thanks. As for now I've changed the pagination value to `false` when no pagination is available.
