### ISSUE TITLE
Fatal error Pinterest error (code: 500)

### ISSUE THREAD

**Issue by zzamyy** [dirkgroenen/Pinterest-API-PHP#101]
when the auth is complete the callback as a defect.

`
Fatal error: Uncaught DirkGroenen\Pinterest\Exceptions\PinterestException: Pinterest error (code: 500) with message: DuplicateBoardSlugException(errorCode=6, message='"{\\"collaborator_invites_enabled\\": false, \\"user_id\\": 589549544878994178, \\"name\\": \\"Test from API\\", \\"private\\": false, \\"protected\\": false, \\"collaborator_requests_enabled\\": false, \\"layout\\": 0, \\"slug\\": \\"test-from-api\\", \\"description\\": \\"Test\\"}"') in C:\xampp\htdocs\vendor\dirkgroenen\pinterest-api-php\src\Pinterest\Transport\Request.php:227 Stack trace: #0 C:\xampp\htdocs\vendor\dirkgroenen\pinterest-api-php\src\Pinterest\Transport\Request.php(98): DirkGroenen\Pinterest\Transport\Request->execute('POST', 'https://api.pin...', Array) #1 C:\xampp\htdocs\vendor\dirkgroenen\pinterest-api-php\src\Pinterest\Endpoints\Boards.php(42): DirkGroenen\Pinterest\Transport\Request->post('boards', Array) #2 C:\xampp\htdocs\API\callback.php(9): DirkGroenen\Pinterest\Endpoints\Boards->create(Array) #3 {main} thrown in C:\xampp\htdocs\vendor\dirkgroenen\pinterest-api-php\src\Pinterest\Transport\Request.php on line 227`

as is pointer the line nive in the callback is empy.
please help me

**Comment by dirkgroenen** [comment]
The error message is quite clear on this one `DuplicateBoardSlugException`. Sounds like you're trying to make a board with a slug that already exists. 

This doesn't look like a problem in the package, but rather your implementation.
