### ISSUE TITLE
Fatal error: Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by cagdaser** [dirkgroenen/Pinterest-API-PHP#103]
hello can you help with my problem?

Fatal error: Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in C:\xampp\htdocs\demo\pinle.php:16 Stack trace: #0 {main} thrown in C:\xampp\htdocs\demo\pinle.php on line 16

**Comment by dirkgroenen** [comment]
Without any code it's going to be hard to help you ;) 

It seems like you're importing the wrong library or something like that. Please follow the guide and make sure your setup matches the documentation. 

Please share more of your code if the problem persists.
