### ISSUE TITLE
Laravel 6 compatibility?

### ISSUE THREAD

**Issue by scottybo** [dirkgroenen/Pinterest-API-PHP#104]
Hi guys,

Just wondering when this package might be ready for Laravel 6?

**Comment by dirkgroenen** [comment]
This has been developed as a stand-alone PHP package, so I guess it should work with Laravel. Is it not?

**Comment by scottybo** [comment]
Good point... Sorry, just going through all my dependencies and didn't think this one through!

**Comment by dirkgroenen** [comment]
No worries ;)
