### ISSUE TITLE
How do you use this library without composer?

### ISSUE THREAD

**Issue by tenold** [dirkgroenen/Pinterest-API-PHP#11]
I can't get this library to load without composer.

I'm using this library with Wordpress inside functions.php if it helps.

**Comment by dirkgroenen** [comment]
I wouldn't recommend doing that, but in case you really want to you probably need to include each separate file in your project. You could write a function which does this automatically for you. There's some information on Google about this. 

I haven't done this before so I can't really help you with it. Checking out this [StackOverflow](http://stackoverflow.com/questions/22388647/how-to-use-a-php-library-with-namespacing-without-composer-as-dependency) thread might help you.
