### ISSUE TITLE
pin send error

### ISSUE THREAD

**Issue by suleymanengintr** [dirkgroenen/Pinterest-API-PHP#111]
I get the following error when sending pin but I couldn't find the solution

Fatal error: Uncaught DirkGroenenPinterestExceptionsPinterestException: Pinterest error (code: 400)

vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php on line 246

**Comment by deindoideas** [comment]
Hi, it's bad request error. Can you post params of pin you are trying to send ?

**Comment by suleymanengintr** [comment]
Notice: Undefined variable: pinid in /var/www/vhosts/domain.com/domain.domain.com/curls.php on line 182

Notice: Undefined variable: pin in /var/www/vhosts/domain.com/domain.domain.com/curls.php on line 188

Notice: Undefined variable: pin in /var/www/vhosts/domain.com/domain.domain.com/curls.php on line 189

Notice: Undefined variable: pin in /var/www/vhosts/domain.com/domain.domain.com/curls.php on line 189

Fatal error: Uncaught DirkGroenen\Pinterest\Exceptions\PinterestException: Pinterest error (code: 400) with message: You need to upload an image or provide the 'image_url' parameter in /var/www/vhosts/domain.com/domain.domain.com/pinte/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php:246 Stack trace: #0 /var/www/vhosts/domain.com/domain.domain.com/pinte/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php(98): DirkGroenen\Pinterest\Transport\Request->execute('POST', 'https://api.pin...', Array) #1 /var/www/vhosts/domain.com/domain.domain.com/pinte/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Endpoints/Pins.php(66): DirkGroenen\Pinterest\Transport\Request->post('pins/?fields=id...', Array) #2 /var/www/vhosts/domain.com/domain.domain.com/curls.php(190): DirkGroenen\Pinterest\Endpoints\Pins->create(Array) #3 {main} thrown in /var/www/vhosts/domain.com/domain.domain.com/pinte/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php on line 246

**Comment by deindoideas** [comment]
You have this error: You need to upload an image or provide the 'image_url' parameter. Are you sending image url on pin creation params ?

**Comment by suleymanengintr** [comment]
Yes, it sends this error on newly launched sites.

**Comment by dirkgroenen** [comment]
This is a Pinterest error, most likely not caused by the package but rather your implementation.

Please share more of your code so we can either reproduce it, or spot the issue.
