### ISSUE TITLE
request empty in create pin

### ISSUE THREAD

**Issue by mtnyvz16** [dirkgroenen/Pinterest-API-PHP#113]
```
$pinInfo = $pinterest->pins->create(array(
	"board"       => $pinterest_board_id,
	"image"       => $data_url,
	"note"        => $pinterest_note,
	"link"        => $post_link
));

$pinInfo = json_decode($pinInfo, true);
print_r($pinInfo);
```

pinterest post is **successful but id is empty.**

output:
```
Array
(
    [id] => 
    [link] => 
    [url] => 
    [creator] => 
    [board] => 
    [created_at] => 
    [note] => 
    [color] => 
    [counts] => 
    [media] => 
    [attribution] => 
    [image] => 
    [metadata] => 
    [original_link] => 
)
```

**Comment by dirkgroenen** [comment]
Seems to be related to https://github.com/dirkgroenen/Pinterest-API-PHP/issues/112

**Comment by mtnyvz16** [comment]
@dirkgroenen  I use the version 0.2.13 you updated on January 27.
Started to do the problem on February 26.
Please check your application.
Thanks.

**Comment by mtnyvz16** [comment]
json:
`{"id":null,"link":null,"url":null,"creator":null,"board":null,"created_at":null,"note":null,"color":null,"counts":null,"media":null,"attribution":null,"image":null,"metadata":null,"original_link":null}`
