### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by berarma** [dirkgroenen/pinterest-api-php#120]
Hi.

I'm wondering about the best way to use the Pinterest API from PHP for a little project I'm working on.

Is this project still compatible with the current Pinterest API?

Is it going to get updates to keep up with the API changes?

Thanks.

**Comment by dirkgroenen** [comment]
Unfortunately I'm no longer maintaining this project. But feel free to open a Pull Request if you find some endpoints to be missing or broken.
