### ISSUE TITLE
paging

### ISSUE THREAD

**Issue by jflefebvre** [dirkgroenen/Pinterest-API-PHP#13]
Thanks for this API client. ;) I was used to webscrap data previously ...
I've noticed an issue about the page property, it's always set to false even if pinterest send the data correctly.

In the Collection class line 90, if I replace the
```
if( is_set($this->response->page) && !empty($this->response->page['next']) ){
```
by 
```
if( is_array($this->response->page) && !empty($this->response->page['next']) ){
```
it does the trick. 
The is_set always return false, weird. I'm using PHP 5.5.30.

**Comment by sfai05** [comment]
I fixed this issue on https://github.com/dirkgroenen/Pinterest-API-PHP/pull/12 :)
Should work after you pull the latest version

**Comment by sfai05** [comment]
+1

**Comment by dirkgroenen** [comment]
Thanks for the tip. I've just changed it and released the new version.

**Comment by dirkgroenen** [comment]
Turns out the problem was caused by the Response class not having a __isset method. I've added this one and written some extra tests and everything seems to be working now.
