### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by zackargyle** [dirkgroenen/Pinterest-API-PHP#14]
No issue. I work on the developer API at Pinterest and came across your project. Just wanted to say thanks, your open-source work is awesome. You're the man!

**Comment by dirkgroenen** [comment]
Great to hear, thanks! Little question since you probably know more about it; what's the deal with the authentication process? I haven't checked it lately (so excuse me if it's already solved), but the last time I did it still didn't match with the documentation.
