### ISSUE TITLE
where is autoload.php?

### ISSUE THREAD

**Issue by technext2k** [dirkgroenen/Pinterest-API-PHP#16]
Hi, I am getting an error about autoload.php. It is included in bootstrap.php as
require __DIR__ . "/../../vendor/autoload.php";

but I don't find it anywhere.

Thanks for your help!

**Comment by dirkgroenen** [comment]
Did your composer install ran successfully?

**Comment by technext2k** [comment]
Thanks for the quick reply. I am sorry, I did not use composer. It's new
for me. Instead I just download the zip package. If using composer is must
I'll try that.

Thanks again.

**Comment by dirkgroenen** [comment]
Jup, please use composer to install the package and include composer's autoload in your project. After that you'll be able to use the api.

**Comment by neerajbhawsar** [comment]
Hi dirkgroenen,

I have download zip folder and after unzip i didn't found 'vendor/autoload.php'.
as per your previous comment i need run composer install, but how can i run composer.
Please explain me step by step.

Thanx

**Comment by dirkgroenen** [comment]
The directory vendor belongs to composer, of which you can find the documentation over [here](https://getcomposer.org/).

In your project you have to require the Pinterest package as dependency `composer require dirkgroenen/Pinterest-API-PHP`, after that you have to run `composer install` which will download the package and create an autoload file in vendor. 

There are many articles and tutorials about composer, so if you need to know more about it (or why you even 'need' it) you can search those up via Google.
