### ISSUE TITLE
PinterestException Codes

### ISSUE THREAD

**Issue by smvanbru** [dirkgroenen/Pinterest-API-PHP#17]
It would be helpful if, when you raised a PinterestException, you set an error code, so our handlers could sort out what sort of error it was in order to handle it appropriately. 

Was there an error in the request? If Pinterest responded with an error, what error was it? (perhaps in Request.php, replacing lines 190-193 with this:
        // Check the response code
        if ( $response->getResponseCode() >= 400 ) {
            throw new PinterestException( 'Pinterest error (code: ' . $response->getResponseCode() . ') with message: ' . $response->message, $response->getResponseCode() );
        }

Thanks!

**Comment by dirkgroenen** [comment]
Added in version 0.2.2.

**Comment by smvanbru** [comment]
Thanks a bunch! This is very helpful.
