### ISSUE TITLE
Undefined index: message in Response

### ISSUE THREAD

**Issue by nWidart** [dirkgroenen/Pinterest-API-PHP#18]
Hello,

I'm using the latest version on this package, and since last time I see there were some changes. Ie: the token isn't returned directly.

Instead a `code` is returned, and we need to get the token from that, if I understand it correctly.

However the following code gives this error:

``` php
$authToken = $this->pinterest->auth->getOAuthToken($code);
```

```
ErrorException in /home/vagrant/liftmetrixapp/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Response.php line 70:
Undefined index: message
```

Did I miss something ?

Thank you.

**Comment by nWidart** [comment]
It seems to be because of this:

``` php
if ( $response->getResponseCode() >= 400 ) {
            throw new PinterestException( 'Pinterest error (code: ' . $response->getResponseCode() . ') with message: ' . $response->message, $response->getResponseCode() );
        }
```
I'm getting a `401` response code, I don't know why ... And the message property doesn't exist.

**Comment by nWidart** [comment]
When I var_dump the `$resonse_data` variable, it has: `"{"error": "invalid_grant"}"`

**Comment by nWidart** [comment]
In the Request class, I dump the following:

``` php
// Execute request and catch response
$response_data = $ch->execute();
dd($ch->getErrors(), $ch->hasErrors(), $response_data);
```

which returns:

```
""
0
"{"error": "invalid_grant"}"
```
So it says it doesn't have any errors, but the `$response_data` does contain an error.

**Comment by dirkgroenen** [comment]
Thanks for your excellent debugging! :+1: 

I might check this one out at the end of the day. The origin of the issue is probably related to Pinterest changing something in their API/oAuth process, but it looks like the response class/error handling of the wrapper needs some updating too.

**Comment by dirkgroenen** [comment]
Ok I just checked some things:

I have a simple running version of the package running on my server which is working fine. The code it's using is the following: 

*boot.php* (required in index.php and callback.php):
```php
require "vendor/autoload.php";

use DirkGroenen\Pinterest\Pinterest;

$pinterest = new Pinterest(secret, secret);

if(isset($_GET["code"])){
    $token = $pinterest->auth->getOAuthToken($_GET["code"]);
    $pinterest->auth->setOAuthToken($token->access_token);
}

if(isset($_GET["access_token"])){
    $pinterest->auth->setOAuthToken($_GET["access_token"]);
}
```

*index.php*:
```html
<body>
    <h1>Login with Pinterest</h1>
    <p>Use this <a href="<?php echo $pinterest->auth->getLoginUrl('https://bitlabs.nl/pinterest/callback.php', array('read_public')); ?>">link to login</a> with your Pinterest account.</p>
</body>
```

*callback.php*:
```html
<h1>Hey you!</h1>
<pre>
    <?php var_dump($pinterest->users->me()); ?>
</pre>
```

Can you check your code against the above?

**Comment by nWidart** [comment]
I have the same setup basically, only in a framework.

I have:

- view 1 which shows link to login
- this redirects to back to `callback` method on controller
- callback method does the `$pinterest->auth->getOAuthToken($_GET["code"]);` , which throws the error mentioned.

**Comment by nWidart** [comment]
Ok I just refreshed the page, and now for some reason I do have an access_token.

I'm not sure what happened.

Sorry for the trouble and thanks for you support! :+1:

**Comment by dirkgroenen** [comment]
Strange stuff happens. Let me know if it somehow comes back.
