### ISSUE TITLE
curl_setopt(): Disabling safe uploads is no longer supported

### ISSUE THREAD

**Issue by veksa** [dirkgroenen/Pinterest-API-PHP#21]
on php7 i got error: "curl_setopt(): Disabling safe uploads is no longer supported" on string 184 "$ch->setOption( CURLOPT_SAFE_UPLOAD, false );" in file "Pinterest-API-PHP/src/Pinterest/Transport/Request.php"

**Comment by dirkgroenen** [comment]
I have no running instance of PHP 7, so I added a possible fix and added PHP 7 to Travis tests. Could you please check version 0.2.4 to see if it's working?

**Comment by veksa** [comment]
yes, now works without error, thanks
