### ISSUE TITLE
Followers Data of Users

### ISSUE THREAD

**Issue by yashasvi12** [dirkgroenen/Pinterest-API-PHP#25]
How can i get list of followers of a user with their username,
this user is not the authenticated user

**Comment by dirkgroenen** [comment]
As you can read in the Pinterest Documentation this ain't possible at the moment. 

https://developers.pinterest.com/docs/api/users/

**Comment by yashasvi12** [comment]
Thank you, I saw some other package on github which offered that option and
was wondering if it was possible
