### ISSUE TITLE
Undefined variable $CURLOPT_MAXREDIRS 

### ISSUE THREAD

**Issue by SerzhEvtushenko** [dirkgroenen/Pinterest-API-PHP#30]
Hi. 
class: /src/Pinterest/Utils/CurlBuilder.php 
method: private function execFollow() 
line: 194
You are using variable $CURLOPT_MAXREDIRS but it is not defined before using.

**Comment by dirkgroenen** [comment]
Thanks, just fixed it.

**Comment by SerzhEvtushenko** [comment]
Thanks
