### ISSUE TITLE
update pin not working

### ISSUE THREAD

**Issue by cheekyboots** [dirkgroenen/Pinterest-API-PHP#34]
Hi,
I see in your documentation that you couldn't get it to work either. However it works through the API Explorer: https://developers.pinterest.com/tools/api-explorer/

I keep getting the error:
Pinterest error (code: 500) with message: cannot concatenate 'str' and 'NoneType' objects' 

The fact that it works through the Explorer (and affects live data) seems like maybe it's an issue with your code.

Thanks.

**Comment by dirkgroenen** [comment]
When I wrote the API wrapper the endpoints didn't work for some reason. I documented it in the README back then:

> https://github.com/dirkgroenen/Pinterest-API-PHP#update-pin
> According to the Pinterest documentation this endpoint exists, but for some reason their API is returning an error at the moment of writing.

Let me check if anything has changed now...

**Comment by dirkgroenen** [comment]
It looks like the error is actually coming from Pinterest, so at this stage there's not much I can do about it.

**Comment by cheekyboots** [comment]
Yes, I know it's coming from Pinterest, and I know you already mentioned it. But did you look at the explorer with the link I posted? They are connecting to the same API and it works on live data, so their API is obviously capable of completing the command.

**Comment by dirkgroenen** [comment]
I haven't checked the api explorer. I did get a comment on my blog from someone who got it to work. I'll give this one some more time, maybe I'll find what's causing it.

**Comment by dirkgroenen** [comment]
Just fixed this in 0.2.9

**Comment by RubenIdeable** [comment]
Hi, 
It seems that is not working in version 0.2.11. Could yo check it please?

**Comment by dirkgroenen** [comment]
Your getting the same error as in the opening post?

**Comment by RubenIdeable** [comment]
Yes, the same error when editting a pin:

Pinterest error (code: 500) with message: cannot concatenate 'str' and 'NoneType' objects'
