### ISSUE TITLE
Notice: Undefined variable: CURLOPT_MAXREDIRS

### ISSUE THREAD

**Issue by compworkmail** [dirkgroenen/Pinterest-API-PHP#35]
Hello. Thanks for nice lib!
I have noticed the error in a code:
Notice: Undefined variable: CURLOPT_MAXREDIRS in .../Pinterest/Utils/CurlBuilder.php on line 194. You need to change 
            if ($CURLOPT_MAXREDIRS > 0) {         
to
            if (CURLOPT_MAXREDIRS > 0) {
(just remove $ sign before CURLOPT). Thanks!

**Comment by dirkgroenen** [comment]
This was already fixed in 0.2.8 https://github.com/dirkgroenen/Pinterest-API-PHP/commit/35f790253f6430387a485c389c69e42688979a86

**Comment by compworkmail** [comment]
Nice, thanks for your great work!
