### ISSUE TITLE
Pinterest error (code: 400) with message: Parameter 'board' is required.

### ISSUE THREAD

**Issue by ibasaw** [dirkgroenen/Pinterest-API-PHP#39]
('POST', 'https://api.pinterest.com/v1/pins', array('image_url' => 'http://tld.com/6b2d6ce3401d3b2cc4f8de5852796a0229645789.jpeg', 'note' => 'test', 'link' => 'http://tld.com/072AE601DF7DB00445386F5C9CC46F74', 'board' => 'username/myboardname')

got this recently, work before...i just update my project with composer update

**Comment by dirkgroenen** [comment]
Sorry, forgot to add the correct post fields to `POST` requests. It's fixed in the new version (0.2.10)

**Comment by ibasaw** [comment]
thx @dirkgroenen
