### ISSUE TITLE
Having issues while creating Pins

### ISSUE THREAD

**Issue by helloarpitgshah** [dirkgroenen/Pinterest-API-PHP#40]
Hey,

Hope you are doing good.

Thanks for adding autoload.php file. it's working Awesome now :)

I have issues with creating the pins now,

Error: Fatal error: Uncaught exception 'DirkGroenen\Pinterest\Exceptions\PinterestException' with message 'Pinterest error (code: 400) with message: Parameter 'board' is required.

Code:

$createBoards = $pinterest->pins->create(array(
				"note"          => "Test board from API",
				"image_url"     => "https://download.unsplash.com/photo-1438216983993-cdcd7dea84ce",
				"board"         => "testappspins"
			));

I have already created  Board with Name "testappspins" within My Pintrest Account.

Can you please help me?

**Comment by dirkgroenen** [comment]
Duplicate, #39

**Comment by helloarpitgshah** [comment]
Hey,

I am still getting the error Fatal error: Uncaught exception 'DirkGroenen\Pinterest\Exceptions\PinterestException' with message 'Pinterest error (code: 400) with message: Parameter 'board' is required.'

Code:

$createBoards = $pinterest->pins->create(array(
                "board"         => "testappspins",
                'image_url'     => 'https://images.unsplash.com/photo-1453974336165-b5c58464f1ed?crop=entropy&fit=crop&fm=jpg&h=1000&ixjsv=2.1.0&ixlib=rb-0.3.5&q=80&w=1925',
                'note'          => 'test',
                'link'          => 'http://tld.com/072AE601DF7DB00445386F5C9CC46F74'
            ));

**Comment by dirkgroenen** [comment]
Have you updated to the latest version?

**Comment by helloarpitgshah** [comment]
Yes, I have update the Latest Version.

I have also created the testappspins at My Users Account. But I also need to create the Board First and then add new pins with the Code.

is i possible to do this?

Can We create the individual pin without creating the Board?

**Comment by dirkgroenen** [comment]
No board, no place to put the pins on. So yeah; you have to create a board first. (As you can read in the [documentation](https://developers.pinterest.com/docs/api/pins/#create-pins)).

The code in 0.2.10 works, guaranteed, so if you're experiencing any problems it's probably your code.

**Comment by helloarpitgshah** [comment]
Yes, Done now :) I miss the username at the Board Name :)

Thanks for your Support, You are Awesome :) 

Do you have instagram API like the same?

**Comment by dirkgroenen** [comment]
Nope, there are already a lot of nice other libs available for Instagram.

**Comment by helloarpitgshah** [comment]
Do you recommended any one, My Friend? Because I also need to post image via API with PHP Code.

But I really need simple PHP Code, :)

**Comment by dirkgroenen** [comment]
Last time I used https://github.com/cosenary/Instagram-PHP-API, but note we're talking about years ago so I don't know how the status is on that one these days.

**Comment by helloarpitgshah** [comment]
Thanks, My Friend :)

Does this allow to post image at the instagram?

**Comment by dirkgroenen** [comment]
I don't know, but I'm not the internet's helpdesk mate. A bit of Googling will answer most of your questions. ;)
