### ISSUE TITLE
Image upload is not working

### ISSUE THREAD

**Issue by sam4jips** [dirkgroenen/Pinterest-API-PHP#47]
I don't know what's broken but it is definitely not working. I have tested it with image_url to make sure there is nothing wrong with my code.

**Comment by dirkgroenen** [comment]
Just checked the code and `image` is indeed broken. Though uploads via `image_url` should work fine. 

Can you please the response you're getting from Pinterest when using `image_url` to make sure it ain't your code which has errors?

**Comment by dirkgroenen** [comment]
Just released a new version with a 'fix'.
