### ISSUE TITLE
Error Loader.php on line 75

### ISSUE THREAD

**Issue by samphors** [dirkgroenen/Pinterest-API-PHP#51]
I got this error when I typed  "composer update" to get vendor folder and after that I started to do nothing, I tried to access to the file, and I saw this message : 

`Fatal error: Uncaught exception 'Dotenv\Exception\InvalidPathException' with message 'Unable to read the environment file at C:\xampp\htdocs\pinterst_fancybox\demo\.env.' in C:\xampp\htdocs\pinterst_fancybox\vendor\vlucas\phpdotenv\src\Loader.php:75 Stack trace: #0 C:\xampp\htdocs\pinterst_fancybox\vendor\vlucas\phpdotenv\src\Loader.php(52): Dotenv\Loader->ensureFileIsReadable() #1 C:\xampp\htdocs\pinterst_fancybox\vendor\vlucas\phpdotenv\src\Dotenv.php(50): Dotenv\Loader->load() #2 C:\xampp\htdocs\pinterst_fancybox\demo\boot.php(9): Dotenv\Dotenv->load() #3 C:\xampp\htdocs\pinterst_fancybox\demo\index.php(1): require('C:\\xampp\\htdocs...') #4 {main} thrown in C:\xampp\htdocs\pinterst_fancybox\vendor\vlucas\phpdotenv\src\Loader.php on line 75`

**Comment by dirkgroenen** [comment]
Dotenv is used in the demo to read app credentials via the environment. You either have to create the `.env` file (as the error message is clearly saying), or remove dotenv from the example code and hard-code your app tokens.
