### ISSUE TITLE
Creating Pins with small images

### ISSUE THREAD

**Issue by csvendsen** [dirkgroenen/Pinterest-API-PHP#53]
If a small image is used for the image_url in $pinterest->pins->create function the function return null without the ability to catch the error or response.
The image url we tested this on is
http://rnajanitorial.com/wp-content/uploads/2015/08/logo.png

**Comment by dirkgroenen** [comment]
Are you sure this isn't a pinterest thing? Can you check the API Explorer output for the pin you created? https://developers.pinterest.com/tools/api-explorer/
