### ISSUE TITLE
$pinterest->following->boards() gives 401 - Anauthorized error

### ISSUE THREAD

**Issue by hrohovakimyan** [dirkgroenen/Pinterest-API-PHP#54]
Here is my code 
$pinterest =  new Pinterest(self::PINTEREST_APP_ID, self::PINTEREST_APP_SECRET);
$pinterest->auth->setOAuthToken($pinterest_access_token);
(I have already got an access token, and as it is permanent credential, I save it in db and retreive every time I need it)
$pinterest->following->boards();
Fatal error: Uncaught exception 'DirkGroenen\Pinterest\Exceptions\PinterestException' with message 'Pinterest error (code: 401) with message: Authorization failed.' in C:\xampp\htdocs\9facts\wp-content\plugins\WJF\Pinterest-API-PHP-master\src\Pinterest\Transport\Request.php on line 238

DirkGroenen\Pinterest\Exceptions\PinterestException: Pinterest error (code: 401) with message: Authorization failed. in C:\xampp\htdocs\9facts\wp-content\plugins\WJF\Pinterest-API-PHP-master\src\Pinterest\Transport\Request.php on line 238

Although
$pinterest->users->getMeBoards(); works fine
Can anyone help

**Comment by dirkgroenen** [comment]
Are you sure your scopes are correct?
