### ISSUE TITLE
Error status 500

### ISSUE THREAD

**Issue by samphors** [dirkgroenen/Pinterest-API-PHP#56]
I have already configured the `.env` file with `appID` and `Secret` from  `Pinterest`. After that I changed the url to my own, but finally I got this such error:

`{"status": "500", "message": "Something failed on our end"}`

my question is how can I know this error mean any why I got it?

here's my url : `https://pinterest-samphors.c9users.io/demo/`

**Comment by manpreet981** [comment]
I am getting the same error as well.
