### ISSUE TITLE
403 error when trying to Pin using token

### ISSUE THREAD

**Issue by evivz** [dirkgroenen/Pinterest-API-PHP#57]
PHP Fatal error:  Uncaught exception 'DirkGroenen\Pinterest\Exceptions\PinterestException' with message 'Pinterest error (code: 403) with message: Forbidden' in /home/customer/pino/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php:227
Stack trace:
#0 /home/customer/pino/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php(98): DirkGroenen\Pinterest\Transport\Request->execute('POST', 'https://api.pin...', Array)
#1 /home/customer/pino/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Endpoints/Pins.php(66): DirkGroenen\Pinterest\Transport\Request->post('pins', Array)
#2 /home/customer/pino/index.php(18): DirkGroenen\Pinterest\Endpoints\Pins->create(Array)
#3 {main}
  thrown in /home/customer/pino/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php on line 227

Fatal error: Uncaught exception 'DirkGroenen\Pinterest\Exceptions\PinterestException' with message 'Pinterest error (code: 403) with message: Forbidden' in /home/customer/pino/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php:227
Stack trace:
#0 /home/customer/pino/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php(98): DirkGroenen\Pinterest\Transport\Request->execute('POST', 'https://api.pin...', Array)
#1 /home/customer/pino/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Endpoints/Pins.php(66): DirkGroenen\Pinterest\Transport\Request->post('pins', Array)
#2 /home/customer/pino/index.php(18): DirkGroenen\Pinterest\Endpoints\Pins->create(Array)
#3 {main}
  thrown in /home/customer/pino/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php on line 227

**Comment by dirkgroenen** [comment]
Are you sure the scopes are correct?

**Comment by dirkgroenen** [comment]
In that case I highly doubt that it has anything to do with the plugin. The plugin catches the error message returned by Pinterest correctly.
