### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by hallmichael** [dirkgroenen/Pinterest-API-PHP#60]
Hi!

Great plugin! So thanks for that! I was just wondering if there is any documentation/notes on pagination calls in your package? I am probably missing something very obvious, I can access the 'next' field showing me the URL to post but unless I hack my own calls I was wondering if it was built in?

```
$boards = $pinterest->following->boards();
echo $boards->pagination['next'] // this prints pinterests next page URL
```

Cheers

**Comment by dirkgroenen** [comment]
I understand how you get confused. To be honest I had to do some searching myself too. Right now you should get a `next` and a `cursor`. Next contains the full and `cursor` can be used to manually specify the next page in the methods `$data` parameter. So for example:

```php
$boards = $pinterest->following->boards();
$pagetwo = $pinterest->following->boards(array('cursor' => $boards['cursor']);
```

An example can also be found in [one of the tests](https://github.com/dirkgroenen/Pinterest-API-PHP/blob/e0f3c8d501b61de0806290326d112a2a4665e38a/tests/Pinterest/Endpoints/FollowingTest.php#L91).

**Comment by hallmichael** [comment]
Thank you! much appreciated!
