### ISSUE TITLE
Composer is giving requirements could not be resolved error.

### ISSUE THREAD

**Issue by 9itish** [dirkgroenen/Pinterest-API-PHP#62]
Hi Dirk, thank you very much for the wrapper. :) 

I can't get it to work, though. When I install the package using composer by typing

`C:\xampp\htdocs\pinterest>composer require dirkgroenen/Pinterest-API-PHP 0.2.11`

I get the following error message:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package dirkgroenen/pinterest-api-php No version set (parsed as 1.0.0) is satisfiable by dirkgroenen/pinterest-api-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

I have not made any changes to the composer.json file. Here is some of its code:

`"require": {
        "php": ">=5.4",
        "ext-curl": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "4.7.*",
        "vlucas/phpdotenv": "^2.2"
    },
    "autoload": {
        "psr-4": {
            "DirkGroenen\\Pinterest\\": "src/Pinterest"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "DirkGroenen\\Pinterest\\Tests\\": "tests/Pinterest"
        }
    }`

Could you please help me resolve this issue?

Thanks.

**Comment by tarekfellah** [comment]
Same issue here

**Comment by crezmer-test** [comment]
same issues here
