### ISSUE TITLE
When I am trying to change the code to an access token, I get this error 

### ISSUE THREAD

**Issue by aammadullah** [dirkgroenen/Pinterest-API-PHP#63]
Notice: Array to string conversion in /home/socialwe/public_html/SWT/SMs/pinterestApi/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php on line 227

Fatal error: Uncaught exception 'DirkGroenen\Pinterest\Exceptions\PinterestException' with message 'Pinterest error (code: 403) with message: Forbidden' in /home/socialwe/public_html/SWT/SMs/pinterestApi/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php:227 Stack trace: #0 /home/socialwe/public_html/SWT/SMs/pinterestApi/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php(98): DirkGroenen\Pinterest\Transport\Request->execute('POST', 'https://api.pin...', Array) #1 /home/socialwe/public_html/SWT/SMs/pinterestApi/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Auth/PinterestOAuth.php(143): DirkGroenen\Pinterest\Transport\Request->post('oauth/token', Array) #2 /home/socialwe/public_html/SWT/SMs/pinterestApi/index.php(18): DirkGroenen\Pinterest\Auth\PinterestOAuth->getOAuthToken('dfb587ef87beaaa...') #3 {main} thrown in /home/socialwe/public_html/SWT/SMs/pinterestApi/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php on line 227

**Comment by walkero-gr** [comment]
We have the same problem on our server. Here it is the apache error log


```
[30-Jun-2017 13:16:23 Europe/Berlin] PHP Fatal error:  Uncaught exception 'DirkGroenen\Pinterest\Exceptions\PinterestException' with message 'Pinterest error (code: 403) with message: Forbidden' in /usr/www/users/xplaiz/pintest2/Pinterest-API-PHP/src/Pinterest/Transport/Request.php:233

Stack trace:
#0 /usr/www/users/xplaiz/pintest2/Pinterest-API-PHP/src/Pinterest/Transport/Request.php(98): DirkGroenen\Pinterest\Transport\Request->execute('POST', 'https://api.pin...', Array)

#1 /usr/www/users/xplaiz/pintest2/Pinterest-API-PHP/src/Pinterest/Auth/PinterestOAuth.php(143): DirkGroenen\Pinterest\Transport\Request->post('oauth/token', Array)

#2 /usr/www/users/xplaiz/pintest2/return.php(14): DirkGroenen\Pinterest\Auth\PinterestOAuth->getOAuthToken('c723756be8f0cb5...')

#3 {main}
  thrown in /usr/www/users/xplaiz/pintest2/Pinterest-API-PHP/src/Pinterest/Transport/Request.php on line 233
```
I guess it might has to do with curl or php-curl, but I didn't find a solution yet...

**Comment by aammadullah** [comment]
I know its reson and can fix it now.

**Comment by walkero-gr** [comment]
can you provide info on why this happens? It might help me to solve this issue on my server too.

**Comment by aammadullah** [comment]
Check it on a different server, 99% chances are that, your IP might be blocked by pinterest

**Comment by walkero-gr** [comment]
I think you are right. The code works just fine from my personal server but not from company's server. Do you think that a proxy server might solve such problem? What solution are you going to use?

**Comment by aammadullah** [comment]
Yes, proxy can solve it.

**Comment by smvanbru** [comment]
If the problem is that they're blacklisting your server, then they don't like what you're doing. Proxy server, changing IP, etc. will temporarily solve the problem, but they're just gonna blacklist any new point of contact you use. To permanently fix the problem, you need to adjust your usage patterns to fit into what they think is reasonable.
