### ISSUE TITLE
Errors in curlbuilder, inc infinite loop

### ISSUE THREAD

**Issue by claudeschneider** [dirkgroenen/Pinterest-API-PHP#66]
I had lots of problems getting things to work on my staging server (turned out to be because CURLfile couldn't fetch remove URLs, only local files). It took hours of debugging, because the curlbuilder class never returns the curl error.

In the process, I found several things that needed changing to make things work for me:

1) ini_get("safe_mode" == "Off") has a code typo - should have been ini_get("safe_mode") == "Off"
However, on some systems it returns "" (and safe_mode is deprecated now anyway:

BEFORE
` if (ini_get("open_basedir") == "" && ini_get("safe_mode" == "Off")) {`
AFTER
```
if (filter_var(ini_get('open_basedir'), FILTER_VALIDATE_BOOLEAN) === false 
&& filter_var(ini_get('safe_mode'), FILTER_VALIDATE_BOOLEAN) === false) {
```

2) Headers aren't sent again on followlocation, so I added an undocumented CURLOPT_POSTREDIR => 3 to make sure we send POST headers again if redirected
https://evertpot.com/curl-redirect-requestbody/
```
CURLOPT_FOLLOWLOCATION => $mr > 0,
CURLOPT_MAXREDIRS => $mr
,CURLOPT_POSTREDIR => 3 // CUSTOM-ADDED - otherwise the POST headers aren't set after redirect
```

3) if we do use FOLLOWLOCATION, it just sets some curl options, but doesn't set $body. It then drops into the code below which calls ->execute() again, which will do exactly the same in an infinite loop, never actually calling curl_exec()

```if (!$body)
{
   $this->setOption(CURLOPT_HEADER, true);
//   $response = $this->execute(); // CUSTOM-REMOVED - this just calls the curlbuilder->execute again and again forever
   $response = curl_exec($this->curl); // CUSTOM-ADDED - use this instead
```

4) Would be really useful to catch any curl errors in curlbuilder and return them.

**Comment by dirkgroenen** [comment]
I'm cleaning up this repo and closing inactive issues. Feel free to comment on this issue if you think it's still relevant.

**Comment by valeriu-dev** [comment]
@dirkgroenen error is relevant
