### ISSUE TITLE
Can i upload 5 image at once in a pin post ad?

### ISSUE THREAD

**Issue by monukanyal** [dirkgroenen/Pinterest-API-PHP#67]
Hello ,
I need to add to the pintrest api the option to add and upload Five(5) Images for each Pin Post Ad, right now the script allows to only Add One(1) Image per Pin Post Ad. is it possible? if yes , how can i do this? please help me.

**Comment by dirkgroenen** [comment]
The API only supports adding one image, so I'm afraid there's not much I can do with this one.
