### ISSUE TITLE
Exceptions: message/code are protected 

### ISSUE THREAD

**Issue by gordielachance** [dirkgroenen/Pinterest-API-PHP#68]
Hi and thanks you for this nice piece of code !
I would like to be able to display errors when the API request fails; but the message and code returned by the exception are protected.  Is this possible ?

                try{
                    $json = pinim()->api->users->me(array('fields' => 'username,first_name,last_name,image[large],counts'));
                    $userdatas = json_decode($json, true);
                }catch (Exception $e) {
                                //get exception message or code here ?
                }

Because for now, when I try to access $e->message, it fires:

> Fatal error: Uncaught Error: Cannot access protected property DirkGroenen\Pinterest\Exceptions\PinterestException::$message in ...

**Comment by dirkgroenen** [comment]
I'm using PHP's default exception class, so in order to get the message you'll have to use the [`getMessage()`](http://php.net/manual/en/exception.getmessage.php) method.
