### ISSUE TITLE
Getting auth token is not working

### ISSUE THREAD

**Issue by albertleao** [dirkgroenen/Pinterest-API-PHP#7]
Hello. I've been following your Auth flow and have gotten stuck on a piece. I have pinterest redirecting back to my app with an access_token in the url. When I pass this access_token into the 
```$pinterest->auth->getOAuthToken($code)``` function, I get the following error.

```
An uncaught Exception was encountered

Type: DirkGroenen\Pinterest\Exceptions\PinterestException

Message: Pinterest error (code: 404) with message: 404: Not Found

Filename: /var/www/dev/vendor/dirkgroenen/pinterest-api-php/src/Pinterest/Transport/Request.php

Line Number: 193
```

**Comment by dirkgroenen** [comment]
As you can read in the README you don't have to get an access_token through the `getOauthToken()` request:

> At this moment the Pinterest API returns the user's access_token in the query string on the callback page. The documentation states that this should be a code, so the next method has been writing assuming this will be changed somewhere in the future

Try using the access_token returned by Pinterest and you should be ready to go.
