### ISSUE TITLE
How can I check if my token is still valid?

### ISSUE THREAD

**Issue by michaeldprice** [dirkgroenen/Pinterest-API-PHP#71]
i have read the docs, and checked the code.

I dont see any way to validate that a stored token is still valid.
Pinterest has a tool on their dev site for token debugger, but dont see it in the api.

Am I missing something here.

I would like to check to make sure that the token i have is still valid, using this api.

**Comment by dirkgroenen** [comment]
Depending on the information you're looking for you could always make a `$pinterest->users->me();` request to check if the token is still valid. If not -> start the authentication procedure.
