### ISSUE TITLE
Pinterest development 

### ISSUE THREAD

**Issue by PavithraHari** [dirkgroenen/Pinterest-API-PHP#74]
1. I need support for Pinterest development without using pinterest login details using only app id and secret key to open the pages. Is that option available 

2. Notice: Undefined offset: 1 in /var/www/html/mansionlibrary_dev/lib_pinterest_api/pinterest_api/vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php on line 71 is this error how to solve i tried  not gte any idea

**Comment by dirkgroenen** [comment]
This is just a wrapper for the official Pinterest API. I can't help you in achieving things their API doesn't support ;) That said as a workaround you could hard-code your own access token into your code and use that for endpoints which require authentication. 

As for the error, this is not an error but a notice so you may ignore it.
