### ISSUE TITLE
Pinterest error (code: 401) with message: Authorization failed

### ISSUE THREAD

**Issue by rohitk82** [dirkgroenen/Pinterest-API-PHP#75]
I am getting 401 error when i tried to fetch username, boards. can you help me why i am getting this?

**Comment by dirkgroenen** [comment]
This is just a wrapper for Pinterest's API, so if it returns a 401 code you might likely not be authorized correctly. Please make sure you have access to the data you're trying to fetch by verifying your scopes and tokens.
