### ISSUE TITLE
Help with Composer

### ISSUE THREAD

**Issue by 1jump2** [dirkgroenen/Pinterest-API-PHP#78]
Can you explain how to use Composer some more please?

I've run 'php composer.phar require dirkgroenen/Pinterest-API-PHP' and it says it's installed, generated autoload files etc but then what?

I'm trying to integrate this with my WordPress plugin. I can't see where the files are to upload.

**Comment by dirkgroenen** [comment]
You can find more information on composer's website (https://getcomposer.org/doc/).
