### ISSUE TITLE
[question] get count of share of specific image

### ISSUE THREAD

**Issue by jd440** [dirkgroenen/Pinterest-API-PHP#79]
Hi everyone,

Does any one know how to get count of share on specific image?
If I have a page with different image we can call:

https://api.pinterest.com/v1/urls/count.json?callback=receiveCount&url=http://example.com

and this will return count of page's share, but we can't know which image have been already share or not!?
Have you any idea?

**Comment by dirkgroenen** [comment]
Closing this issue. This is not an issue or question related to this library (which only wraps endpoints provided by pinterest).
