### ISSUE TITLE
Unable to submit App

### ISSUE THREAD

**Issue by vishal2647** [dirkgroenen/Pinterest-API-PHP#81]
Hi Guys,

Everything is working fine and collaborators are able to get access token and create pins. 

Problem is when I am submitting my app for final review, I am getting "502 Bad Gateway" response on pressing the blue "Submit" button. Tried different browsers but no luck. Any idea why this is happening? And how I can tell Pinterest about this?

**Comment by dirkgroenen** [comment]
This is just a PHP library that wraps the Pinterest API. Contact Pinterest for any Pinterest specific questions.
