### ISSUE TITLE
Implement Section endpoints

### ISSUE THREAD

**Issue by kishan93** [dirkgroenen/Pinterest-API-PHP#84]
i wanted to use https://developers.pinterest.com/docs/api/sections/
has anyone came up with code ?

**Comment by dirkgroenen** [comment]
This is not in there yet, I'll write it down as a FR. Thanks.

**Comment by dirkgroenen** [comment]
This will be in release [0.2.12](https://github.com/dirkgroenen/Pinterest-API-PHP/pull/102)
