### ISSUE TITLE
Problems with authentication

### ISSUE THREAD

**Issue by prappo** [dirkgroenen/Pinterest-API-PHP#86]
Tried to get the list of the boards . I used this code 
```
$bot = PinterestBot::create();

// Login

        $bot->auth->login('mylogin', 'mypassword',false);

// Get lists of your boards
        $boards = $bot->boards->forMe();
        print_r($boards);
```

This code is working on my local server but when I tried it on my live web server it's occurring errors

> AuthRequired in ProviderWrapper.php line 66:
>Error calling seregazhuk\PinterestBot\Api\Providers\Boards::forMe method. You must log in before.

My login details are correct so what is the problem?

**Comment by dirkgroenen** [comment]
Looks like you're in the wrong repo, this is the `dirkgroenen/pinterest-api-php` package. Please check https://github.com/seregazhuk/php-pinterest-bot for support.
