### ISSUE TITLE
Add attribution link to pin

### ISSUE THREAD

**Issue by UVLabs** [dirkgroenen/Pinterest-API-PHP#87]
How would you add the link from which a pin originated as seen here? https://www.pinterest.com/pin/617063586420559182/

![image](https://user-images.githubusercontent.com/10324144/44819144-c2c83400-abb9-11e8-95b5-eb6b1032ddf0.png)

**Comment by dirkgroenen** [comment]
You could try checking the `link` or `original_link` properties on the Pin?
