### ISSUE TITLE
Infinite loop in CurlBuilder

### ISSUE THREAD

**Issue by WhatsOn** [dirkgroenen/Pinterest-API-PHP#88]
The CurlBuilder enters an infinite loop on any CURL error.

To reproduce try creating a pin using a file that does not exist.

**Comment by dirkgroenen** [comment]
Closing due inactivity, please let me know if this is still an issue.

**Comment by valeriu-dev** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/14403446/223219971-67e8ba8d-d70e-4e89-9a93-dc89eb7dd5e8.png">
