### ISSUE TITLE
How to use fromBoard method? 

### ISSUE THREAD

**Issue by VadimSS** [dirkgroenen/Pinterest-API-PHP#90]
I am used this method this way:

$resp = $pinterest->pins->fromBoard('giftsbrains/gifts-for-women', $data = []);

But I got just first 25 pins from this board. How I can fetch all the pins from this board?
 I have no idea how ho use  array $data parameter of this function, and what fields this array must include.

**Comment by dirkgroenen** [comment]
Please check the documentation section [Collection](https://github.com/dirkgroenen/Pinterest-API-PHP#collection)

**Comment by dirkgroenen** [comment]
Responses with multiple instances are returned as a `Collection`. This class has the option to check a next page using [`hasNextPage()`](https://github.com/dirkgroenen/Pinterest-API-PHP#check-if-collection-has-next-page). If a next page is available you can retrieve the `cursor` from the collection and pass it along as `$data = ['cursor' => $cursor]` to your method.

**Comment by dirkgroenen** [comment]
This will be in release [0.2.12](https://github.com/dirkgroenen/Pinterest-API-PHP/pull/102)
