### ISSUE TITLE
New Section

### ISSUE THREAD

**Issue by misterkek** [dirkgroenen/Pinterest-API-PHP#91]
How I can get Pins from https://www.pinterest.ru/following/ page?

**Comment by dirkgroenen** [comment]
This is mentioned in the docs: https://github.com/dirkgroenen/Pinterest-API-PHP#following

For the actual implementation see the [Following.php](https://github.com/dirkgroenen/Pinterest-API-PHP/blob/2dcffb7d4f4ffbc9a43ea962d79ebcda3b06efce/src/Pinterest/Endpoints/Following.php) class.
