### ISSUE TITLE
Request to correct instructions

### ISSUE THREAD

**Issue by robincsamuel** [dirkgroenen/Pinterest-API-PHP#92]
I noticed a deprecation warning.

`Deprecation warning: require.dirkgroenen/Pinterest-API-PHP is invalid, it should not contain uppercase characters. Please use dirkgroenen/pinterest-api-php instead. Make sure you fix this as Composer 2.0 will error.`

It'd be great to correct the instructions to say `composer require dirkgroenen/pinterest-api-php`

**Comment by dirkgroenen** [comment]
Thanks, it's fixed in #93

**Comment by dirkgroenen** [comment]
This will be in release [0.2.12](https://github.com/dirkgroenen/Pinterest-API-PHP/pull/102)
